seed: 1116
dataset:
  train: "moco_debug_train.csv"
  valid: "moco_debug_valid.csv"
params:
  epochs: 2
  batch_size: 4
  test_batch_size: 4
  es_rounds: 10
  verbose: 1
  num_workers: 2
model:
  model_name: "resnet18"
  pretrained: null # e.g. 'imagenet'
optim:
  name: "Adam"
  params:
    - lr: 0.001
scheduler:
  name: "CosineAnnealingLR"
  params:
    - T_max: 10
transform:
  - name: RandomBlur
    params:
      prob: 0.2
  - name: RandomNoise
    params:
      prob: 0.2
  - name: CoarseDropout
    params:
      prob: 0.2
  - name: GridDistortion
    params:
      prob: 0.2
  - name: ElasticTransform
    params:
      prob: 0.2
  - name: RandomBrightnessContrast
    params:
      prob: 0.2
  - name: ShiftScaleRotate
    params:
      prob: 0.2
