seed: 1116
dataset:
  train: "moco_train_20.csv"
  valid: "moco_valid_20.csv"
params:
  epochs: 100
  batch_size: 128
  test_batch_size: 128
  es_rounds: 10
  verbose: 1
  num_workers: 8
others:
  name: null # "mixup" or "cutmix" or null
  alpha: 0.2
  use_grapheme: False
model:
  model_name: "resnet18"
  pretrained: True
optim:
  name: "Adam"
  params:
    - lr: 0.001
scheduler:
  name: "CosineAnnealingLR"
  params:
    - T_max: 10
transform:
  - name: RandomBlur
    params:
      prob: 0.2
  - name: GaussNoise
    params:
      prob: 0.2
  - name: CoarseDropout
    params:
      prob: 0.2
  - name: GridDistortion
    params:
      prob: 0.2
  - name: ElasticTransform
    params:
      prob: 0.2
  - name: RandomBrightnessContrast
    params:
      prob: 0.2
  - name: ShiftScaleRotate
    params:
      prob: 0.2
