seed: 1116
dataset:
  train: "moco_train_unseen.csv"
  valid: "moco_valid_unseen.csv"
params:
  epochs: 100
  batch_size: 64
  test_batch_size: 64
  es_rounds: 60
  verbose: 1
  num_workers: 8
others:
  name: null # "mixup" or "cutmix" or null
  alpha: 0.3
  use_grapheme: False
  dataset: "train_images"
model:
  model_name: "GhostNet"
  pretrained: True
optim:
  name: "Adam"
  params:
    - lr: 0.01
scheduler:
  name: "ReduceLROnPlateau"
  params:
    - mode: "min"
    - factor: 0.1
    - patience: 10
transform:
  - name: RandomBlur
    params:
      prob: 0.4
  - name: MultiplicativeNoise
    params:
      prob: 0.4
  - name: GridDistortion
    params:
      prob: 0.4
  - name: ElasticTransform
    params:
      prob: 0.4
  - name: ShiftScaleRotate
    params:
      prob: 0.4
