seed: 1116
dataset:
  train: "moco_train_10.csv"
  valid: "moco_valid_10.csv"
params:
  epochs: 2
  batch_size: 16
  test_batch_size: 4
  es_rounds: 10
  verbose: 1
  num_workers: 2
others:
  name: "cutmix" # "mixup" or "cutmix" or null
  use_grapheme: False
model:
  model_name: "resnet18"
  pretrained: True
optim:
  name: "Adam"
  params:
    - lr: 0.001
scheduler:
  name: "ReduceLROnPlateau"
  params:
    - mode: "min"
    - patience: 2
transform:
  - name: RandomBlur
    params:
      prob: 0.2
  - name: GridDistortion
    params:
      prob: 0.2
  - name: ElasticTransform
    params:
      prob: 0.2
  - name: ShiftScaleRotate
    params:
      prob: 0.2
  - name: CoarseDropout
    params:
      prob: 0.2
  - name: RandomAugMix
    params:
      prob: 0.2
  - name: RandomMorphology
    params:
      prob: 0.2
