version: '2.4'
services:
  python:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    runtime: nvidia
    container_name: bengali
    command: /bin/bash
    working_dir: /home
    tty: true
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHON_PATH=/home
    ports:
      - 7999:8888
    volumes:
      - ./:/home
