seed: 1116
params:
  epochs: 4
  batch_size: 4
  es_rounds: 10
  verbose: 1
model:
  name: "se_resnext50_32x4d"
  pretrained: null # e.g. 'imagenet'
optim:
  name: "Adam"
  params:
    - lr: 0.001
scheduler:
  name: "CosineAnnealingLR"
  params:
    - T_max: 10
