seed: 1116
dataset:
  train: "moco_train_20.csv"
  valid: "moco_valid_20.csv"
params:
  epochs: 200
  batch_size: 16
  es_rounds: 10
  verbose: 10
  num_workers: 4
model:
  name: "se_resnext50_32x4d"
  pretrained: "imagenet" # e.g. 'imagenet'
optim:
  name: "Adam"
  params:
    - lr: 0.001
scheduler:
  name: "CosineAnnealingLR"
  params:
    - T_max: 10
transform:
  - name: RandomBlur
    params:
      prob: 0.2
  - name: RandomNoise
    params:
      prob: 0.2
  - name: CoarseDropout
    params:
      prob: 0.2
  - name: GridDistortion
    params:
      prob: 0.2
  - name: ElasticTransform
    params:
      prob: 0.2
  - name: RandomBrightnessContrast
    params:
      prob: 0.2
  - name: ShiftScaleRotate
    params:
      prob: 0.2
